import Sidebar from './Sidebar/layout'
import './globals.css'
import { Inter, Open_Sans } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const openSans = Open_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Hello Kelsey',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <main className="app">
        {children}
        <Sidebar />
        </main>
      </body>
    </html>
  )
}
